spring:
  datasource:
    url: jdbc:postgresql://database/webcrawler_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changeLog.xml
app:
  crawler:
    thread-count: 6
    link-depth: 2
    max-visited-pages: 100

logging:
  level:
    com:
      softeq:
        webcrawler:
          DEBUG
