spring:
  datasource:
    url: jdbc:postgresql://database/webcrawler_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changeLog.xml
app:
  crawler:
    thread-count: 5
    default-link-depth: 8
    default-max-visited-pages: 10000

logging:
  level:
    com:
      softeq:
        webcrawler:
          DEBUG
      gargoylesoftware:
        htmlunit:
          OFF