spring:
  datasource:
    url: jdbc:postgresql://gateway.docker.internal:5432/webcrawler_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase-changeLog.xml
    enabled: true

app:
  crawler:
    thread-count: 6
    link-depth: 2
    #max-visited-pages: 10001
    max-visited-pages: 100

logging:
  level:
    com:
      softeq:
        webcrawler:
          DEBUG
